# Generated by Django 2.0.3 on 2018-03-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='regex',
            field=models.TextField(default='.*'),
        ),
    ]
